#!/bin/sh /etc/rc.common

START=70
STOP=70

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

run_global()
{
    local enable
    config_get_bool enable $1 enable
    if [ "$enable" -eq "1" ]; then
        echo $enable
        fxagent 172.17.60.148:4001 & 
        echo "fxagent enabled." >/dev/console  
    else
        echo $enable
        echo "fxagent disabled." >/dev/console
        killall -kill fxagent
    fi  
}

start() 
{
    config_load fxagent
    config_foreach run_global global
}

stop()
{
    echo ...
}
